# Generated by Django 4.0.5 on 2022-06-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0004_remove_jobs_position_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_stories', models.CharField(max_length=255)),
                ('content_stories', models.CharField(max_length=255)),
                ('date_stories', models.DateTimeField()),
            ],
        ),
    ]
