# Generated by Django 4.0.5 on 2022-06-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0005_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='content_stories',
            field=models.TextField(),
        ),
    ]
