# Generated by Django 4.0.5 on 2022-06-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0006_alter_stories_content_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('useremail', models.EmailField(max_length=254)),
                ('about', models.TextField()),
            ],
            options={
                'db_table': 'apply',
            },
        ),
    ]
