# Generated by Django 4.0.5 on 2022-06-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0007_apply_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('pozita', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
