# Generated by Django 4.0.5 on 2022-06-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0008_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
    ]
