# Generated by Django 4.0.5 on 2022-06-12 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0009_apply_job_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='experienc',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='Yes', max_length=10),
        ),
    ]
