# Generated by Django 4.0.5 on 2022-06-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0010_apply_job_experienc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='sex',
        ),
        migrations.AddField(
            model_name='apply_job',
            name='F',
            field=models.BooleanField(default=False, verbose_name='Female'),
        ),
        migrations.AddField(
            model_name='apply_job',
            name='M',
            field=models.BooleanField(default=False, verbose_name='Male'),
        ),
    ]
