# Generated by Django 4.0.5 on 2022-06-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0011_remove_apply_job_sex_apply_job_f_apply_job_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='F',
        ),
        migrations.RemoveField(
            model_name='apply_job',
            name='M',
        ),
        migrations.AddField(
            model_name='apply_job',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
    ]
