# Generated by Django 4.0.5 on 2022-06-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0012_remove_apply_job_f_remove_apply_job_m_apply_job_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='experienc',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
    ]
