# Generated by Django 4.0.5 on 2022-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0017_alter_jobs_position_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply_job',
            name='sex',
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='experienc',
            field=models.CharField(max_length=10),
        ),
    ]
