# Generated by Django 4.0.5 on 2022-06-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0019_rename_experienc_apply_job_pozition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_job',
            old_name='pozition',
            new_name='positionjob',
        ),
    ]
