# Generated by Django 4.0.5 on 2023-03-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0020_rename_pozition_apply_job_positionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply_job',
            name='coverletter',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='apply_job',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='positionjob',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='apply_job',
            table=None,
        ),
    ]
