# Generated by Django 4.0.5 on 2023-03-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0021_apply_job_coverletter_apply_job_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply_job',
            old_name='useremail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='positionjob',
            field=models.CharField(choices=[('Backend Developer', 'Backend Developer'), ('Fullstack Developer', 'Fullstack Developer'), ('Frontend Developer', 'Frontend Developer'), ('Fullstack Developer internship', 'Fullstack Developer internship')], max_length=255),
        ),
    ]
