# Generated by Django 4.0.5 on 2023-03-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0022_rename_useremail_apply_job_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='coverletter',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='apply_job',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
