# Generated by Django 4.0.5 on 2023-03-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupcompany', '0025_delete_user_contact_content_alter_contact_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
